const results = [
  [
    'Katarina',
    'Leona',
    'Lux',
    'Twitch',
    'Twisted Fate',
    'Ezreal',
    'Blitzcrank'
  ],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Zyra', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Zyra', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Zyra', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Darius', 'Ekko', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Darius', 'Ekko', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Vi', 'Blitzcrank', 'Trundle'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Vi', 'Blitzcrank', 'Trundle'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ezreal', 'Ziggs', 'Poppy'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ezreal', 'Ziggs', 'Poppy'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ezreal', 'Ziggs', 'Poppy'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Ziggs', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Ziggs', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Ziggs', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Ziggs', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Ziggs', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Vex', 'Kassadin'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Vex', 'Kassadin'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Blitzcrank', 'Vex', 'Kassadin'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ziggs', 'Janna', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ziggs', 'Janna', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ziggs', 'Janna', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ziggs', 'Janna', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Twitch', 'Ziggs', 'Janna', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Twisted Fate', 'Zyra', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Twisted Fate', 'Darius', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Garen', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Garen', 'Blitzcrank', 'Ziggs'],
  [
    'Katarina',
    'Leona',
    'Lux',
    'Lissandra',
    'Blitzcrank',
    'Ziggs',
    'Heimerdinger'
  ],
  [
    'Katarina',
    'Leona',
    'Lux',
    'Lissandra',
    'Blitzcrank',
    'Ziggs',
    'Heimerdinger'
  ],
  [
    'Katarina',
    'Leona',
    'Lux',
    'Lissandra',
    'Blitzcrank',
    'Ziggs',
    'Heimerdinger'
  ],
  [
    'Katarina',
    'Leona',
    'Lux',
    'Lissandra',
    'Blitzcrank',
    'Ziggs',
    'Heimerdinger'
  ],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Ziggs', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Ziggs', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Ziggs', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Ziggs', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Janna', 'Talon'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Janna', 'Talon'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Janna', 'Talon'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Blitzcrank', 'Janna', 'Talon'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Poppy', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Poppy', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Poppy', 'Janna'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Janna', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Janna', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Janna', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Lissandra', 'Ziggs', 'Janna', 'Shaco'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Garen', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Garen', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Fiora'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Fiora'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Fiora'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Warwick', 'Ekko', 'Ziggs', 'Braum'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Dr. Mundo', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Dr. Mundo', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Dr. Mundo', 'Blitzcrank', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Darius', 'Trundle', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Vi', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Vi', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Trundle', 'Vex'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Trundle', 'Vex'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Trundle', 'Vex'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Ekko', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Ekko', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Ekko', 'Ziggs'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Ekko', 'Kassadin'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Blitzcrank', 'Ekko', 'Kassadin'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Trundle', 'Ekko', 'Poppy'],
  ['Katarina', 'Leona', 'Lux', 'Zac', 'Trundle', 'Ekko', 'Poppy'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Twisted Fate', 'Trundle', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Swain', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr.Mundo', 'Swain', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Malzahar', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Malzahar', 'Blitzcrank', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Blitzcrank', 'Trundle', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Blitzcrank', 'Trundle', 'Ekko'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Blitzcrank', 'Trundle', 'Talon'],
  ['Katarina', 'Leona', 'Lux', 'Dr. Mundo', 'Blitzcrank', 'Trundle', 'Talon']
]
